name: Android Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.400'  # Use the correct version for your project

      - name: Debug File Structure
        run: ls -R

      - name: Install dependencies
        run: dotnet restore C:\Users\amihlk\source\repos\automation\TgAzureAQA\Team.LHTests\Team.LHTests.sln

      - name: Build the Project
        run: dotnet build C:\Users\amihlk\source\repos\automation\TgAzureAQA\Team.LHTests\Team.LHTests.sln --configuration Release

      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --log appium.log &  # Start Appium in background

      - name: Run Tests
        run: dotnet test C:\Users\amihlk\source\repos\automation\TgAzureAQA\Team.LHTests\Team.LHTests.sln --logger "trx;LogFileName=test-results.trx"
