name: Android Test Automation (C# + SpecFlow)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.400'  # Adjust based on project

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: dotnet restore

      # Step 4: Build the Test Suite
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      # Step 5: Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Step 6: Start Appium Server (Wait to ensure it's ready)
      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --log-level info &
          sleep 10  # Give Appium time to start

      # Step 7: Ensure TestResults Directory Exists
      - name: Ensure TestResults Directory Exists
        run: mkdir -p TestResults

      # Step 8: Run SpecFlow Tests
      - name: Run SpecFlow Tests
        run: dotnet test --logger trx --results-directory TestResults/
        continue-on-error: true  # Allow workflow to continue if tests fail

      # Step 9: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults/
